sudo: required

language: bash

services:
  - docker

before_install:
  - make prepare

script:
  - make build
  - make test
  - cd 2.3.2.0 && make build && make test
  - cd 2.3.2.0/packer && make build && make test
  - cd python2.7/2.3.2.0 && make build && make test
  - cd python2.7/2.6 && make build && make test
