schemaVersion: '2.0.0'
commandTests:
  - name: "ansible installation"
    command: "pip"
    args: ["show", "ansible"]
    expectedOutput: [
        "ansible\n",
        "Version: 2.3.2.0\n",
        ]

  - name: "packer installation"
    command: "which"
    args: ["packer"]
    expectedOutput: [
        "/usr/bin/packer\n",
        ]

  - name: "packer version"
    command: "packer"
    args: ["--version"]
    expectedOutput: [
        "1.1.3\n",
        ]
