# The base image is python 2.7
FROM python:2.7

# Author: Roy Evangelista
MAINTAINER Roy Evangelista <royevangelista@gmail.com>

# Install ansible
RUN pip install ansible==2.3.2.0

# Copied from base image
CMD ["python"]
