schemaVersion: '2.0.0'
commandTests:
  - name: "ansible installation"
    command: "pip"
    args: ["show", "ansible"]
    expectedOutput: [
        "ansible\n",
        "Version: 2.3.2.0\n",
        ]
