# The base image is python 3 alpine
FROM python:2.7

# Author: Roy Evangelista
MAINTAINER Roy Evangelista <royevangelista@gmail.com>

# Install ansible
RUN pip install ansible==2.6.1

# Copied from base image
CMD ["python"]
